### ISSUE TITLE
granate barfs on double quotes in comments

### ISSUE THREAD

**Issue by nicolaiskogheim** [granateio/granate#17] opened 2017-07-30 18:09 UTC
```graphql
# A temporary endpoint to check that the server is alive and working
type Pinger {
    # Is always "pong"
    answer: String!
}

type Query {
    ping: Pinger
}
```

I get garbage in my `schema/definitions.go`.

Remove the quotes in ` # Is always "pong"` and it works fine.

**Comment by Nohac** [comment] 2017-07-30 19:59
Duplicate of #13

**Closed as completed by Nohac** 2017-07-30 19:59 UTC
